# CHAPTER 01. 파이썬 기반의 머신러닝과 생태계 이해

## 01. 머신러닝의 개념

머신러닝의 개념은 다양하게 표현할 수 있으나, 일반적으로는 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법을 통칭한다.

#### 머신러닝의 분류
##### 지도학습
- 분류
- 회귀
- 추천시스템
- 시각/음성 감지/인지
- 텍스트 분석, NLP

##### 비지도 학습
- 클러스터링
- 차원 축소
- 강화학습

#### 데이터 전쟁
머신러닝의 가장 큰 단점은 데이터에 매우 의존적이다. 좋은 품질의 데이터를 갖추지 못한다면 머신러닝의 수행결과도 좋을 수 없다.
최적의 머신러닝 알고리즘과 모델 파라미터를 구축하는 능력도 중요하지만, 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 더 중요하다. 

## 02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

- 머신러닝 패키지 : 대표적인 머신러닝 패키지는 사이킷런(Scikit-Learn)
- 행렬/선형대수/통계 패키지 : 행렬과 선형대수를 다루는 패키지는 넘파이(NumPy), 자연과학과 통계를 위한 다양한 패키지를 가진건 사이파이(SciPy)
- 데이터 핸들링 : 판다스. 특히 2차원 데이터 처리에 특화되어 있으며 넘파이보다 훨씬 편리하게 데이터 처리할 수 있는 많은 기능을 제공한다.
- 시각화 : 맷플롯립(Matplotlib). 하지만 너무 세분화된 API를 가지고 있어 번거롭고 디자인부분에서도 투박한 면이 있다. 이를 보완하기 위해 시본(Seaborn)이 있다. 시본은 맷플롯립을 기반으로 만들었지만, 판다스와의 쉬운 연동, 더 함축적인 API, 분석을 위한 다양한 유형의 그래프/차트 제공 등으로 인기를 얻고 있다. 


## 03.넘파이

### 넘파이(Numerical Python)
: 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원한다. 
- 루프를 사용하지 않고 대량 데이터의 배열 연산을 가증하게 하므로 빠른 배열 연산 속도를 보인다. 
- C/C++과 같은 저수준 언어 기반의 호환 API를 제공한다.
    - (넘파이는 매우 빠른 배열 연산을 보장해주지만, 파이썬 언어자체가 가지는 수행 성능의 제약이 있으므로 수행 성능이 매우 중요한 부분은 C/C++ 기반의 코드로 작성하고 이를 넘파이에서 호출하는 방식으로 통합 할 수 있음)
- 다양한 데이터 핸들링 기능을 제공한다.
     - 하지만 편의성과 다양한 API 지원 측면에서 아쉬운 부분이 많다.(보통 데이터는 2차원 형태의 행과 열로 이루어졌으니, 이에 대한 다양한 가공과 변환, 여러가지 통계용 함수의 적용 등이 필요하니) 그래서 판다스의 편리성에는 미치지 못한다.

### 넘파이 ndarray 개요

In [1]:
# 넘파이 임포트하기
import numpy as np

넘파이의 기본 데이터 타입은 ndarray이다. 이를 이용해 넘파이에엇 다차원 배열을 쉽게 생성하고 다양한 연산을 수행 할 수 있다.

- np.array()함수 : 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환하는 기능이다. ndarray로 변환을 원하는 객체를 인자로 입력하면 된다.
- array이름.shape : ndarray의 차원과 크기를 튜플 형태로 나타낸다.

In [3]:
# 1차원 array로 3개의 데이터를 가지고 있음
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

# 2차원 rray로, 2개의 로우와 3개의 칼럼으로 구성되어 6개의 데이터를 가지고 있음
array2 = np.array([[1, 2, 3],
                 [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

# 2차원 array로 1개의 로우와 3개의 칼럼으로 구성되어 3개의 데이터를 가지고 있음
array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
# 각 array 차원을 확인해보자
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### ndarray의 데이터 타입
- 연산의 특성상 같은 데이터 타입만 가능하다. 즉, 한개의 ndarray 객체에 int와 float가 함께 있을 수 없다.

In [7]:
# 데이터 타입은 dtype 속성으로 확인
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면, 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [9]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- astype() 메서드 : ndarray내 데이터값의 타입 변경하기
    - 대용량의 ndarray를 만들때 많은 메모리가 사용되는데, 메모리를 더 절약해야 할 떄 보통 이용한다. 

In [10]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

arange( ) : array를 range( )로 표현하는 것. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터 값으로 변환해준다.

In [12]:
sequence_array = np.arange(10) # default 함수인자는 stop값이다.
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


zeros( ): 함수인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환

ones( ): zeros와 유사하게 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다.

In [13]:
# 두 메서드 다 dtype 정해주지 않으면 default로 float64형의 데이터로 채운다.
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

reshape( ) : ndarray를 특정 차원 및 크기로 변환한다. 변환을 원하는 크기를 함수 인자로 부여하면 된다.

In [14]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
# 지정된 사이즈로 변경이 불가능하면 오류를 발생한다.
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

실전에서 더욱 효율적으로 사용하는 경우 : 인자로 -1을 적용하는 경우

원래 ndarray와 호환되는 새로운 shape로 변환해준다.

In [16]:
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

array2 shape: (2, 5)
array3 shape: (5, 2)


In [17]:
# -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없다.
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

-1 인자는 reshape(-1,1)과 같은 형태로 자주 사용된다.

stack이나 concat으로 결합할때 각각의 ndarray의 형태를 통일해 유용하게 사용된다. 이는 어떤 형태라도 2차원이고, 여러개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환되는 것을 보장하기 때문이다.

In [18]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist()) # tolist() : 리스트 자료형으로 변환

# 3차원 -> 2차원
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 -> 2차원
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

: 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 한다.
1. 특정한 데이터만 추출 
2. 슬라이싱(Slicing)
3. 팬시 인덱싱(Fancy Indexing)
4. 불린 인덱싱(Boolean Indexing)

#### 단일 값 추출
: 1개의 데이터값을 선택하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 [ ]안에 입력하면 된다.

In [20]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출할 수 있다.

In [21]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [22]:
# 데이터값도 간단히 수정 가능하다
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


2차원의 경우, 콤마로분리된 로우와 칼럼 위치의 인덱스를 통해 접근한다.

In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


- axis = 0 : 로우 방향의 축
- axis = 1 : 컬럼 방향의 축
- [row=0, col=1]인덱싱은 [axis 0=0, axis 1=1]이 정확한 표현이다
- 3차원 ndarray의 경우는 axis 0, axis1, axis 2로 3개의 축을 가지게 된다

#### 슬라이싱
: ':'기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있다. 
- 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray타입.
- ':'사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1위치에 있는 데이터 ndarray를 반환한다.

In [25]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>



1. : 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주한다.
2. : 기호 뒤에 종료 인덱스를 생갹하면 자동으로 맨 마지막 인덱스로 간주한다.
3. : 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주한다.

In [26]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [29]:
# 2차원 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0]) # 축 한쪽에만 슬라이싱을 적용하고 다른쪽에는 단일 값 인덱스 적용가능

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]


- 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다.
- 3차원에서는 뒤에오는 인덱스 없애면 2차원 반환함

In [32]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


#### 팬시 인덱싱
: 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식이다.

In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2]-->', array3.tolist()) # 리스트 자료형으로 변환

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2]-->', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]]-->', array5.tolist())

array2d[[0, 1], 2]--> [3, 6]
array2d[[0, 1], 0:2]--> [[1, 2], [4, 5]]
array2d[[0, 1]]--> [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱
: 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용된다.
- 이를 이용하면 for loop/ if else문보다 훨씬 간단하게 구현가능하다.
- [ ]내에 조건문을 그대로 기재하기만 하면 된다

불린 인덱싱이 동작하는 단계
1. array1d > 5와 같이 ndarray의 필터링 조건을 [ ] 안에 기재
2. False값은 무시하고 True 값에 해당하는 인덱스값만 저장(유의 사항은 True값 자체인 1을 저장하는 것이 아니라, True값을 가진 인덱스를 저장함)
3. 저장된 인덱스 데이터 세트로 ndarray 조회

In [35]:
array1d = np.arange(start=1, stop=10)
# [ ]안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [36]:
# 위의 조건 필터링 알아보기 
array1d> 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [37]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [38]:
# 밑과 같이 인덱스 집합을 만들어 대입한 것과 동일하다
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort( )와 argsort( )

#### 행렬 정렬
- 넘파이의 행렬 정렬은 np.sort( )와 같이 넘파이에서 sort( )를 호출하는 방식, ndarray.sort( )와 같이 행렬자체에서 호출하는 방식이 있다.
- 두 방식의 차이
    - np.sort( ) : 원 행렬은 그대로 유지한 채 원행렬의 정렬된 행렬을 반환
    - ndarray.sort( ) : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

In [40]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)
print('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 정렬 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


- 둘다 기본적으로 오름차순으로 정렬한다.
- 내림차순으로 정렬하기 위해서는 [::-1]을 적용한다.


In [41]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우에 axis 축값 설정을 통해 로우 도는 칼럼 방향으로 정렬을 수행할 수 있다.

In [43]:
array2d = np.array([[8, 12],
                 [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환하기
: 원본 행렬이 정렬되었을 떄, 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort( )를 이용한다.
- 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환함

In [44]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


- 내림차순 정렬시에 원본 행렬의 인덱스를 구하는 것도 [::-1]를 적용하면 된다.

In [46]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- argsort( )는 넘파이에서 매우 활용도가 높다. ndarray는 RDBMS의 TABLE 칼럼이나 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없다. 따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야한다.

In [47]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#### 행렬 내적(행렬 곱)
: 행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot( )을 이용하여 계산한다.
- 행렬 내적의 특성상, 왼ㅉ고 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능하다

In [49]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7, 8],
             [9, 10],
             [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


#### 전치 행렬
: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 전치행렬이라고 한다. np.traspose( )를 이용하면 구할 수 있다.
- 행렬 A의 전치 행렬은 A^T와 같이 표기한다.

In [51]:
transpose_mat = np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

A의 전치행렬:
 [[1 4]
 [2 5]
 [3 6]]


## 04. 데이터 핸들링 - 판다스

- 일반적으로 대부분의 데이터 세트는 2차원 데이터이다. 행과 열로 구성되어 있다. 판다스는 이처럼 2차원 데이터를 효율적으로 가공/처리 할 수 있는 다양하고 훌륭한 기능을 제공한다.
- 넘파이보다 훨씬 유연하고 편리하게 데이터 핸들링을 가능하게 해준다.
- 판다스는 파이썬의 리스트, 컬렉션, 넘파이 등의 내부 데이터뿐만 아니라 CSV 등의 파일을 쉽게 데이터프레임으로 변경해 데이터의 가공/분석을 편리하게 수행할 수 있게 만들어준다.
- 판다스의 핵심 객체는 DataFrame이다. DataFrame은 여러개의 행과 열로 이뤄진 2차원 데이터를 담는 데이터 구조체이다. 
- Index는 개별 데이ㅓ를 고유하게 식별하는 Key값이다. Series와 DataFrame은 모두 Index를 Key값으로 가지고 있다.
- Series와 DataFrame의 가장 큰 차이는 시리즈는 칼럼이 하나뿐이니 데이터 구조체이고, 데이터프레임은 칼럼이 여러개인 데이터 구조체라는 것이다.
- DataFrame은 여러 개의 Series로 이뤄졌다고 할 수 있다. 
- 판다스는 csv, tab과 같은 다양한 유형의 분리 문자로 칼럼을 분리한 파일을 손쉽게 데이터프레임으로 로딩할 수 있게 해준다.

### 판다스 시작 - 파일을 DataFrame으로 로딩, 기본 API

In [29]:
import pandas as pd

- read_csv() : CSV(칼럼을 ','로 구분한 파일 포맷) 파일 포맷 변환을 위한 API이다.
    - CSV뿐만 아니라 어떤 필드 구분 문자 기반의 파일 포맷도 데이터프레임으로 변환이 가능하다. read_csv()인자인 sep에 해당 구분 문자를 입력하면 된다.
    - 예) read_csv('파일명', sep='\t')
    - 함수에서 가장 중요한 인자는 파일 경로이다. Filepath에 로드하려는 데이터 파일의 경로를 포함한 파일명을 입력하면 된다.
- read_table() : 디폴트 필드 구분문자는 탭('\t')이다.
    - read_csv()와 기능상으로는 큰 차이가 없다.
- read_fwf() : Fixed Width, 즉 고정길이 기반의 칼럼 포맷을 데이터프레임으로 로딩한다.

In [30]:
titanic_df = pd.read_csv('/Users/wizdom/Desktop/data_analysis/Kaggle_titanic/titanic/train.csv')
titanic_df.head(3) # DataFrame.head() : 맨 앞에 있는 N개의 로우를 반환

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [31]:
print('titanic 변수 type:', type(titanic_df))

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


- pd.read_csv()는 호출 시 파일명 인자로 들어온 파일을 로딩해 DataFrame 객체로 반환한다.
    - 별다른 파라미터 지정이 없으면 파일의 맨 처음 로우를 칼럼명으로 인지하고 칼럼으로 변환한다.
    - 콤마로 분리된 데이터값들이 해당 칼럼에 맞게 할당한다.
- 모든 데이터프레임 내의 데이터는 생성되는 순간 고유의 인덱스 값을 가지게 된다.

- 데이터프레임의 행과 열의 크기를 알아보는 가장 좋은 방법 : shape 변수 이용.
    - 데이터프레임의 행과 열을 튜플 형태로 반환

In [32]:
print('DataFrame 크기:', titanic_df.shape)

DataFrame 크기: (891, 12)


- info() 메서드 : 총 데이터 건수와 데이터 타입, Null 건수를 알 수 있다.

In [33]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


- describe() 메서드 : 칼럼별 숫자형 데이터 값의 n-percentile 분포도, 평균값, 최솟값, 최댓값을 나타낸다. 오직 숫자형칼럼의 분포도만 조사한다.
    - describe 메서드만으로 정확한 분포도는 알기 무리지만, 개략적인 수준의 분포도를 확인할 수 있어 유용하다.
    - 또한 해당 숫자 칼럼이 숫자형 카테고리 칼럼인지를 판단할 수 있게 도와준다
    - < 각 인덱스 의미 >
    - count : Not Null인 데이터 건수
    - mean : 전체 데이터의 평균값
    - std : 표준편차
    - min : 최솟값 / max : 최댓값
    - 00% : 각 %값

In [34]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

- value_count() : 해당 칼럼값의 유형과 건수를 확인할 수 있다. 이는 데이터의 분포도를 확인하는데 매우 유용한 함수이다.

In [35]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


- 데이터프레임의 [ ]연산자 내부에 칼럼명을 입력하면 해당 칼럼에 해당하는 시리즈 객체를 반환한다.

In [36]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


- Series : Index와 단하나의 칼럼으로 구성된 데이터 세트

In [37]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

왼쪽이 인덱스, 오른쪽은 시리즈의 해당칼럼의 값
- 모든 시리즈와 데이터프레임은 인덱스를 반드시 가진다 !!

- value_count()가 반환하는 데이터 타입 역시 시리즈이나, 왼쪽 인덱스를 보면 단순히 0부터 시작하는 순차값이 아니다.
- 이처럼 인덱스는 단순히 순차 값과 같은 의미 없는 식별자만 할당하는 것이 아니라, 고유성이 보장된다면 의미 있는 데이터값 할동도 가능하다
    - value_count()는 칼럼 값별 데이터 건수를 반환하므로 고유칼럼 값을 식별자로 사용할 수 있다.
    - 인덱스는 데이터프레임, 시리즈가 만들어진 후에도 변경 할 수 있다.
    - 인덱스는 또한 숫자형뿐만 아니라 문자열도 가능하다
    - 단, 모든 인덱스는 고유성이 보장돼야 한다.

### DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호변환
#### 넘파이 ndarray, 리스트, 딕셔너리를 DataFrame으로 변환하기
- DataFrame은 파이썬의 리스트, 딕셔너리, 그리고 넘파이 ndarray등으로 변환될 수 있다.
- 데이터프레임은 리스트와 넘파이 ndarray와 다르게 칼럼명을 가지고 있다. 이로 인해 상대적으로 편하게 데이터 핸들링이 가능하다.
- 데이터프레임으로 변환 시 칼럼명을 지정해준다.(지정하지 않으면 자동으로 칼럼명 할당)
- 판다스 데이터프레임 객체의 생성인자 data는 리스트나 딕셔너리 또는 넘파이 ndarray를 입력 받고, 생성 인자 컬럼은 칼럼명 리스트를 입력받아서 쉽게 데이터 프레임을 생성할 수 있다.

In [38]:
import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

# 리스트를 이용해 데이터프레임 생성.
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

# 넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [39]:
# 2차원 형태의 데이터를 기반으로 데이터프레임 생성

# 2행 3열 형태
col_name2 = ['col1', 'col2', 'col3']

# 리스트와 ndarray 생성한 뒤 이를 데이터프레임으로 변환
list2 = [[1, 2, 3],
        [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


딕셔너리를 DataFrame으로 변환
- 딕셔너리의 키는 칼럼명으로, 딕셔너리의 값은 키에 해당하는 칼럼 데이터로 변환된다. 
- 따라서 키의 경우는 문자열, 값의 경우 리스트(또는 ndarray) 형태로 딕셔너리를 구성한다.

In [40]:
# 키는 문자열 칼럼명으로 매핑, 값은 리스트형 칼럼 데이터로 매핑
dict = {'col1':[1, 11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print(df_dict)

   col1  col2  col3
0     1     2     3
1    11    22    33


#### DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기
- 데이터프레임을 넘파이 ndarray로 변환하는 것은 데이터프레임 객체의 values를 이용해 쉽게 할 수 있다.

In [41]:
array3 = df_dict.values
print('type:', type(array3), 'shape:', array3.shape)
print(array3)

type: <class 'numpy.ndarray'> shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


- DataFrame -> 리스트 변환 : values로 얻은 ndarray에 tolist( ) 호출
- DataFrame -> 딕셔너리 변환 : 데이터프레임 객체의 to_dict( ) 호출. 인자로 'list'입력

In [42]:
list3 = df_dict.values.tolist()
print('타입:', type(list3))
print(list3)

dict3 = df_dict.to_dict('list')
print('타입:', type(dict3))
print(dict3)

타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]
타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


### DataFrame의 칼럼 데이터 세트 생성과 수정
- [  ] 연산자를 이용해 쉽게 할 수 있다.
    - [  ] 내에 새로운 칼럼명을 입력하고 값을 할당해주기만 하면 된다

In [43]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0

- Series에 상숫값을 할당하면 Series의 모든 데이터 세트에 일괄적으로 적용된다. 이는 넘파이의 ndarray에 상숫값을 할당할 떄 모든 ndarray값에 일괄 적용됨과 동일하다

In [44]:
titanic_df['Age_by_10'] = titanic_df['Age'] * 10
titanic_df['Family_No'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      220.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      380.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      260.0          1

In [45]:
# 기존 칼럼 값도 쉽게 일괄적으로 업데이트 가능
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

### DataFrame 데이터 삭제
: drop( ) 메서드를 이용한다.

원형

DataFrame.drop(labels=None, axis=0, index=None, columns=None, level=None, inplace=False, errors='raise')
- 여기서 중요한 파라미터는 labels, axis, inplace이다.

- axis값에 따라서 특정 칼럼 또는 특정 행을 드롭한다.
    - axis 0은 로우 방향축, axis 1은 칼럼 방향 축이다.
    - label에 원하는 칼럼 명 입력하고 axis를 입력하면 지정된 칼럼 또는 로우를 드롭한다.
    - DataFrame의 특정 로우를 가리키는 것은 인덱스이다. 따라서 axis를 0으로 지정하면 DataFrame은 자동으로 labels에 오는 값을 인덱스로 간주한다.

In [46]:
titanic_drop_df = titanic_df.drop('Age_0', axis = 1)
titanic_drop_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      360.0          1

- inplace = False : 자기자신의 데이터프레임의 데이터는 삭제하지 않으며, 삭제된 결과 데이터프레임을 반환한다.
- inplace = True : 자신의 데이터프레임의 데이터를 삭제한다. 
- 여러개의 칼럼을 삭제하고 싶으면 리스트 형태로 삭제하고자 하는 칼럼 명을 입력해 labels 파라미터로 입력하면 된다.

In [47]:
titanic_df.head(3)

PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_0  Age_by_10  Family_No
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      0      320.0          2
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      0      480.0          2
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      0      360.0          1

inplace = False가 디폴드 값이므로 'Age_0' 칼럼이 존재한다. (titanic_drop_df에서 삭제된것)

In [48]:
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print('inplace=True로 drop후 반환된 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop후 반환된 값: None


PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

- 한가지 유의할점은 drop()시 inplace=True로 설정하면 반환 값이 None(아무값도 아님)이 된다. 따라서 위와 같이 inplace=True로 설정한 채 반환 값을 다시 자신의 데이터프레임 객체로 할당하면 안된다.

In [49]:
# axis = 0일때
# set_option : 지정된 옵션의 값을 설정함
pd.set_option('display.width', 1000) # 문자로 표시되는 너비 설정
pd.set_option('display.max_colwidth', 15) # 최대문자너비. 오버플로 되면 ...나온다.
print(' ### before axis 0 drop ### ')
print(titanic_df.head(3))

titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print(' ### after axis 0 drop ### ')
print(titanic_df.head(3))

 ### before axis 0 drop ### 
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
 ### after axis 0 drop ### 
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q


### Index 객체
: 데이터프레임, 시리즈의 레코드를 고유하게 식별하는 객체.
- index만 추출하려면 DataFrame.index, Series.index속성을 통해 가능하다.

In [1]:
import pandas as pd
titanic_df = pd.read_csv('/Users/wizdom/Desktop/data_analysis/Kaggle_titanic/titanic/train.csv')

# index 객체 추출
indexes = titanic_df.index
print(indexes)

# index 객체를 실제 값 array로 반환
print('index 객체 array값:', indexes.values)

RangeIndex(start=0, stop=891, step=1)
index 객체 array값: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 

- 단일 값 반환 및 슬라이싱도 가능

In [2]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


- 한번 만들어진 데이터프레임 및 시리즈의 인덱스 객체는 함부로 변경할 수 없다.

In [3]:
indexes[0] = 5

TypeError: Index does not support mutable operations

- 시리즈 객체는 index객체를 포함하지만 시리즈 객체에 연산 함수를 적용할 때, index는 연산에서 제외된다. index는 오직 !식별용!으로만 사용한다.

In [4]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n', (series_fair + 3).head(3))

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


- reset_index() : 새롭게 인덱스를 연속 숫자 형으로 할당하며 기존 인덱스는 'index'라는 새로운 칼럼 명으로 추가한다.\
    - 인덱스가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용한다.
    - 이를 적용하면 Series가 DataFrame이 반환되니 유의 !
    - parameter 중 drop=True로 설정하면 기존 인덱스는 새로운 칼럼으로 추가되지 않고 삭제된다.

In [5]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
print('### before rest_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

### before rest_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


### 데이터 셀레션 및 필터링
#### DataFrame의 [ ] 연산자
- DataFrame 바로 뒤에 있는 [ ] 안에 들어갈 수 있는 것은 칼럼 명 문자(또는 칼럼 명의 리스트 객체), 또는 인덱스로 변환 가능한 표현식이다.
    - 즉, 데이터프레임 뒤에 있는 [ ]는 칼럼만 지정할 수 있게 '칼럼 지정 연산자'로 이해하면 된다.

In [10]:
print('단일 컬럼 데이터 추출:\n', titanic_df['Pclass'].head(3))

# 여러개 칼럼 추출(리스트 객체 이용)
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))

print('\n [ ] 안에 숫자 인덱스는 오류 발생:\n', titanic_df[0])

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

- 판다스의 인덱스 형태로 변환 가능한 표현식은 [ ] 내에 입력할 수 있으나, 사용하지 않는 것이 좋다.

In [11]:
titanic_df[0:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

- 불린 인덱싱 표현도 가능

In [13]:
titanic_df[titanic_df['Pclass']== 3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

#### DataFrame ix[ ] 연산원
- 행 위치 지정은 데이터프레임의 인덱스 값을 입력해야한다. 열 위치 지정은 칼럼 명 뿐만 아니라, 칼럼의 위치값 지정도 가능
    - ix[0, 'Pclass]와 같이 행 위치 지정으로 인덱스값 0, 열 위치 지정으로 칼럼 명인 'Pclass'를 입력해 원하는 위치의 데이터를 추출 할 수 있다.
    - 행과 열 둘다 명칭과 위치 기반 인덱싱 모두 허용
- 하지만 코드가 혼돈을 주거나 가독성이 떨어져 판다스에서 사라지게 되었다.
- ndarray의 [ ] 연산자와 동일하게 단일 지정, 슬라이싱, 불린 인덱싱, 팬시 인덱싱 모두 가능

In [14]:
print('칼럼 위치 기반 인덱싱:', titanic_df.ix[0, 2])
print('칼럼 명 기반 인덱싱:', titanic_df.ix[0, 'Pclass'])

AttributeError: 'DataFrame' object has no attribute 'ix'

#### 명칭 기반 인덱싱과 위치 기반 인덱싱의 구분
- 명칭(label) 기반 인덱싱 : 칼럼의 명칭을 기반으로 위치를 지정하는 방식. '칼럼 명' 같이 명칭으로 열 위치 지정
- 위치(Position) 기반 인덱싱을 0을 출발점으로 하는 가로축, 세로축 좌표 기반의 행과 열 위치를 기반으로 데이터 지정. 따라서 행, 열 값으로 정수가 입력된다.

In [17]:
data = {'Name':['chulmin', 'eunkyung', 'jinwoong', 'soobeom'],
       'Year':[2011, 2016, 2015, 2015],
       'Gender':['Male', 'Female', 'Male', 'Female']}

data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])

# data_df를 reset_index()로 새로운 숫자형 인덱스를 생성
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index':'old_index'})

# 인덱스값에 1을 더해서 1부터 시작하는 새로운 인덱스값 만들기
data_df_reset.index = data_df_reset.index + 1
data_df_reset

old_index      Name  Year  Gender
1       one   chulmin  2011    Male
2       two  eunkyung  2016  Female
3     three  jinwoong  2015    Male
4      four   soobeom  2015  Female

In [ ]:
# 오류 발생
data_df_reset.ix[0,1]

- 인덱스가 int형인 경우, ix[0,1]은 행의 위치 값으로 위치기반 인덱스 값을 사용하는 것이 아니라, 데이터프레임의 인덱스 값을 사용한다. 따라서 인덱스 값이 0인 키는 찾을 수 없다.

In [ ]:
# 첫번째 행 2번째 열 위치에 있는 데이터값 반환
data_df_reset.ix[1,1]

이렇게 행 위치에 적용되는 인덱스값과 위치 기반 인덱싱이 정수형일때 코드 작성에 혼선을 초래한다.

- 데이터프레임의 인덱스값은 명칭 기반 인덱싱이라고 간주한다. 

#### DataFrame iloc[ ] 연산자
: 위치 기반 인덱싱만 허용. 정수 또는 정수형의 슬라이싱, 팬시 리스트 값을 입력해줘야한다.
- 명확한 위치 기반 인덱싱이 사용되어야 하는 제약으로 불린 인덱싱은 제공하지 않는다.

In [19]:
# 첫번째 행, 첫번째 열의 데이터 추출
data_df.iloc[0, 0]

'chulmin'

In [20]:
# 위치 인덱싱이 아닌 명칭을 입력하면 오류가 발생한다.
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [21]:
# 문자열 인덱스를 행 위치에 입력해도 오류 발생
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [22]:
# 1부터 시작하는 새로운 정수형 인덱스 값
data_df_reset.iloc[0, 1]

'chulmin'

DataFrame loc[ ]연산자
: 명칭 기반으로 데이터를 추출한다.
- 행 위치에는 데이터프레임의 인덱스 값, 열 위치에는 칼럼 명을 입력해준다.

In [23]:
data_df.loc['one', 'Name']

'chulmin'

- !!!! 인덱스가 숫자 형일 수 있기 때문에 명칭 기반이라고 무조건 문자열을 입력한다는 선입견을 가져서는 안된다 !

In [24]:
data_df_reset.loc[1, 'Name']

'chulmin'

In [25]:
# 인덱스 값이 0인 행이 없으므로 오류
data_df_reset.loc[0, 'Name']

KeyError: 0

- loc[ ]에 슬라이싱 기호 ':'를 적용할 때 한가지 유의 할 점
    - 종료 값 -1이 아니라 종료 값가지 포함한다. 
    - 명칭은 숫자 형이 아닐 수 있기 때문에 -1을 할 수가 없다 !

In [26]:
print('위치 기반 iloc:\n', data_df.iloc[0:1, 0])
print('\n명칭 기반 loc:\n', data_df.loc['one':'two', 'Name'])

위치 기반 iloc:
 one    chulmin
Name: Name, dtype: object

명칭 기반 loc:
 one     chulmin
two    eunkyung
Name: Name, dtype: object


In [27]:
# 인덱스가 정수형일때 조심하기
# 인덱스 값에 따른 명칭 기반 인덱싱이므로 2개의 데이터 반환
print(data_df_reset.loc[1:2, 'Name'])

1     chulmin
2    eunkyung
Name: Name, dtype: object


#### 불린 인덱싱
: 매우 편이한 데이터 필터링 방식
- [ ], ix[ ], lox[ ]에서 공통으로 지원(iloc[ ]는 X)

In [28]:
titanic_df = pd.read_csv('/Users/wizdom/Desktop/data_analysis/Kaggle_titanic/titanic/train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

- 칼럼이 두개 이상일때는 [ [ ] ]를 사용한다.

In [30]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

- loc[ ]를 이용할때는 [ ['Name', 'Age']]는 칼럼 위치에 놓여야한다.

In [32]:
titanic_df.loc[titanic_df['Age']>60, ['Name', 'Age']].head(3)

Name   Age
33           Wheadon, Mr. Edward H  66.0
54  Ostby, Mr. Engelhart Cornelius  65.0
96       Goldschmidt, Mr. George B  71.0

- 개별 조건은 ( )로 묶고 복합 조건 연산자를 이용한다.
    - and : &, or : |, Not : ~

In [33]:
titanic_df[ (titanic_df['Age']>60) & (titanic_df['Pclass']==1) & (titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [34]:
# 개별 조건을 변수에 할당하고, 이들 변수를 결합하여 불린 인덱싱 수행할 수 있다.
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

### 정렬, Aggregation 함수, GroupBy 적용
#### DataFrame, Series의 정렬 - sort_values( )
: DataFrame과 Series의 정렬을 위해서 sort_values( )를 이용한다.
- 주요 입력 파라미터
    - by : by로 특정칼럼을 입력하면 해당 칼럼으로 정렬을 수행한다.
    - ascending : =True(기본)로 설정하면 오름차순, False로 설정하면 내림차순 정렬한다.
    - inplace : =False(기본)로 설정하면 sort_value()를 호출한 데이터프레임은 그대로 유지하며 정렬된 데이터프레임을 결과로 반환한다. 
      True로 설정하면 호출한 데이터프레임의 정렬결과를 그대로 적용한다.

In [35]:
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass                              Name     Sex  \
845          846         0       3               Abbing, Mr. Anthony    male   
746          747         0       3       Abbott, Mr. Rossmore Edward    male   
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female   

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845  42.0      0      0  C.A. 5547   7.55   NaN        S  
746  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  35.0      1      1  C.A. 2673  20.25   NaN        S

In [37]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
282          283         0       3        de Pelsmaeker, Mr. Alfons  male   

      Age  SibSp  Parch    Ticket  Fare Cabin Embarked  
868   NaN      0      0    345777   9.5   NaN        S  
153  40.5      0      2  A/5. 851  14.5   NaN        S  
282  16.0      0      0    345778   9.5   NaN        S

#### Aggregation 함수 적용
- 데이터프레임에서 바로 aggregation을 호출할 경우 모든 칼럼에 적용한다.

In [38]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [39]:
# 특정 칼럼에 aggregation함수 적용하기
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

#### groupby( ) 적용
- 분석 작업에 매우 많이 활용한다.
- by 파라미터에 칼럼을 입력하면 대상 칼럼으로 groupby된다.
- 데이터프레임에 groupby()를 호출하면 DataFrameGroupBy라는 또다른 형태의 데이터프레임을 반환한다.

In [40]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


- 데이터프레임에 groupby()를 호출해 반환된 결과에 aggregation 함수를 호출하면 groupby() 대상 칼럼을 "제외"한 모든 칼럼에 aggregation 함수를 적용한다.

In [41]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

- groupby()에 특정 칼럼만 aggregation 함수를 적용하려면 groupby()로 반환된 DataFrameGroupBy 객체에 해당 칼럼을 필터링한 뒤 aggregation함수를 적용한다.

In [43]:
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

- 여러 개의 aggregation함수를 사용할떄에는 DataFrameGroupBy 객체의 agg( )내에 인자로 입력해서 사용한다.

In [44]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

- api 기반으로 처리하다보니 SQL의 group by보다 유연성이 떨어진다.
- agg( )내에 입력 값으로 딕셔너리 형태로 aggregation이  적용될 칼러믇ㄹ과 aggregation함수를 입력한다.

In [46]:
agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

### 결손 데이터 처리하기
: 칼럼에 값이 없는, 즉 NULL인 경우. 넘파이의 NaN으로 표시한다.
- NaN 값은 평균, 총합 등의 함수 연산 시 제외가 된다. 

#### isna( )로 결손 데이터 여부 확인
: 데이터가 NaN인지 아닌지를 알려준다. 데이터프레임에 isna()를 수행하면 모든 칼럼의 값이 NaN인지 아닌지를 True나 False로 알려준다.

In [47]:
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

- 결손 데이터 개수 구하기 : isna()결과에 sum()함수를 추가해 구할 수 있다.(True는 1로, False는 0으로 변환됨)

In [48]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

#### fillna( )로 결손 데이터 대체하기
: fillna()를 이용하면 결손 데이터를 편하게 다른 값으로 대체할 수 있다.

In [50]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

- 주의 ! fillna()를 이용해 반환값을 다시 받거나  inplace=True 파라미터를 추가해야 실제 데이터 세트 값이 변경된다.

In [52]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

### apply lambda 식으로 데이터 가공
: apply 함수에 lambda 식을 결합해 데이터프레임이나 시리즈의 레코드 별로 데이터를 가공하는 기능을 제공한다.
- 복잡한 데이터 가공이 필요할 경우 사용(판다스는 칼럼에 일괄적으로 데이터 가공을 하는것이 속도 면에서는 빠름)
- 람다는 함수 선언과 함수 내의 처리를 한 줄의 식으로 쉽게 변환하는 식이다.

In [55]:
lambda_squre = lambda x : x ** 2
print(lambda_squre(3))

9


- ':'로 입력 인자와 반환될 입력 인자의 계산식을 분리한다.
    - 왼쪽은 입력 인자를 가리키며, 오른쪽은 입력인자의 계산식(반환 값)을 의미한다.
- 여러 개의 값을 입력 인자로 사용해야 할 경우에는 보통 map()함수를 결합해 사용한다.

In [56]:
a = [1, 2, 3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [57]:
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [58]:
# if else절을 이용하여 복잡한 가공 하기
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

- ! 주의할 점 ! if 절의 경우 if 식보다 반환 값을 먼저 기술해야한다.(: 기호의 오른편에 반환 값이 있어야 하기 때문)
    - else는 else식이 먼저 나오고 반환 값이 나중에 오면 된다.
- else if는 지원하지 않는다. 이를 이용하려면 else 절을 ( )로 내포해 ( )내에서 다시 if else 적용해 사용한다.

In [59]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

- else if가 많이 나와야 하는 경우나 switch case 문의 경우는 별도의 함수를 만드는게 더 나을 수 있다.

In [60]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age) :
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'
        
    return cat

# lambda 식이 위에서 생성한 get_category() 함수를 반환값으로 지정.
# get_category(x)는 입력값으로 'Age'칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age', 'Age_cat']].head()

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult